version: '3.7'

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/data/pg
      - POSTGRES_PASSWORD=secret
    volumes:
      - "./data:/data"
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"

